apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-app-deployment
  template:
    metadata:
      labels:
        app: crud-app-deployment
    spec:
      containers:
        - name: crud-app
          image: madan09/crudopr:v1
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-host
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-name
---
apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  selector:
    app: crud-app-deployment
  ports:
    - protocol: TCP
      port: 80       # Port exposed within the cluster
      targetPort: 5000 # Port your application is listening on
  type: NodePort    # Expose the service using a NodePort
