apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  database-host: <your encoded host url>
  database-user: <your encoded user name>
  database-password: <your encoded password>
  database-name: <your encoded database name>
