apiVersion: v1
kind: Secret
metadata:
  name: your-secret
type: Opaque
data:
  database-host: bXlkYXRhYmFzZTEyMy5teXNxbC5kYXRhYmFzZS5henVyZS5jb20=
  database-user: bWFkYW4wOQ==
  database-password: a29obGlAMTIz
  database-name: dXNlcnM=
