apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  selector:
    app: crud-app-deployment
  ports:
    - protocol: TCP
      port: 80       # Port exposed within the cluster
      targetPort: 5000 # Port your application is listening on
  type: NodePort    # Expose the service using a NodePort

